### ISSUE TITLE
doesn't work !!!

### ISSUE THREAD

**Issue by vivalarival** [FlaminSarge/tf2attributes#10]
L 10/05/2017 - 09:05:23: [tf2attributes.smx] Could not initialize call to CEconItemSchema::GetItemDefinition
L 10/05/2017 - 09:05:23: [tf2attributes.smx] Could not initialize call to CEconItemView::GetSOCData
L 10/05/2017 - 09:05:23: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName
L 10/05/2017 - 09:05:23: [SM] Exception reported: Could not initialize call to GEconItemSchema
L 10/05/2017 - 09:05:23: [SM] Blaming: tf2attributes.smx
L 10/05/2017 - 09:05:23: [SM] Call stack trace:
L 10/05/2017 - 09:05:23: [SM]   [0] SetFailState
L 10/05/2017 - 09:05:23: [SM]   [1] Line 131, tf2attributes.sp::OnPluginStart
L 10/05/2017 - 09:05:23: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)

**Comment by FlaminSarge** [comment]
need more logs than that

**Comment by vivalarival** [comment]
exactly what logs do you need?

**Comment by FlaminSarge** [comment]
You're currently missing anything before or after the snippet you posted.

**Comment by FlaminSarge** [comment]
You should also include your OS and other info about your SM setup.
