### ISSUE TITLE
i had a problem whit tf2attributes 

### ISSUE THREAD

**Issue by tiomack** [FlaminSarge/tf2attributes#16]
sm plugins list
[SM] Listing 22 plugins:
  01 "Admin File Reader" (1.8.0.6025) by AlliedModders LLC
  02 "Admin Help" (1.8.0.6025) by AlliedModders LLC
  03 "Admin Menu" (1.8.0.6025) by AlliedModders LLC
  04 "Anti-Flood" (1.8.0.6025) by AlliedModders LLC
  05 "Basic Ban Commands" (1.8.0.6025) by AlliedModders LLC
  06 "Basic Chat" (1.8.0.6025) by AlliedModders LLC
  07 "Basic Comm Control" (1.8.0.6025) by AlliedModders LLC
  08 "Basic Commands" (1.8.0.6025) by AlliedModders LLC
  09 "Basic Info Triggers" (1.8.0.6025) by AlliedModders LLC
  10 "Basic Votes" (1.8.0.6025) by AlliedModders LLC
  11 "[TF2] Chat Tag" (3.5.0) by John B.
  12 "Client Preferences" (1.8.0.6025) by AlliedModders LLC
  13 <Failed> "[Source 2013] Custom Chat Colors" (3.1.0) by Dr. McKay
  14 "Fun Commands" (1.8.0.6025) by AlliedModders LLC
  15 "Fun Votes" (1.8.0.6025) by AlliedModders LLC
  16 "Nextmap" (1.8.0.6025) by AlliedModders LLC
  17 "Player Commands" (1.8.0.6025) by AlliedModders LLC
  18 "Reserved Slots" (1.8.0.6025) by AlliedModders LLC
  19 <Error> "Roll The Dice (Revamped)" (1.02) by Phil25
  20 "Sound Commands" (1.8.0.6025) by AlliedModders LLC
  21 <Error> "[TF2] TF2Attributes" (1.2.1) by FlaminSarge
  22 <Failed> "tf2attributes_example.smx"
Errors:
custom-chatcolors.smx ([Source 2013] Custom Chat Colors): Could not find r
d plugin "scp"
rtd.smx (Roll The Dice (Revamped)): Depends on plugin: tf2attributes.smx
tf2attributes.smx ([TF2] TF2Attributes): Error detected in plugin startup
rror logs)
tf2attributes_example.smx: Could not find required plugin "tf2attributes"

i start to do server like 8 monts ago so i dont known a lot of sourcemod but really i serch a lot how to fix this but i cant , i want install rtd plugin but i need tf2attributes, so i need help

**Comment by FlaminSarge** [comment]
Please seek help on the AlliedMods forum regarding installation.
