### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by Alicebnd** [FlaminSarge/tf2attributes#17]
Hello.
I have a random crashes on my servers (linux) with old and new version tf2attributes plugin.
I have not errors in log, but unload tf2attributes stop the crashes.
My https://crash.limetech.org/2lwzqdy7zlbs

**Comment by FlaminSarge** [comment]
I'm pretty sure this isn't due to tf2attributes, but due to a plugin that uses tf2attributes. Investigate those. My guess would be an ff2 or custom weapon plugin.
