### ISSUE TITLE
Unable to load plugin "tf2attributes.smx" tf2attributes.sp::OnPluginStart

### ISSUE THREAD

**Issue by tarantazzz** [FlaminSarge/tf2attributes#19]
L 02/06/2018 - 15:15:57: [SM] Exception reported: Could not initialize call to CAttributeList::SetRuntimeAttributeValue
L 02/06/2018 - 15:15:57: [SM] Blaming: tf2attributes.smx
L 02/06/2018 - 15:15:57: [SM] Call stack trace:
L 02/06/2018 - 15:15:57: [SM]   [0] SetFailState
L 02/06/2018 - 15:15:57: [SM]   [1] Line 176, C:\sourcemod\tf2attributes\tf2attributes.sp::OnPluginStart
L 02/06/2018 - 15:15:57: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)

AAAAAAAAAAAAAWAWWWWWWWWWWW

**Comment by FlaminSarge** [comment]
You're gonna need to provide more information than that.

**Comment by FlaminSarge** [comment]
Duplicate of #12
