### ISSUE TITLE
tf2attribute falling to load correctly

### ISSUE THREAD

**Issue by unown294** [FlaminSarge/tf2attributes#2]
I followed all the instructions on how to install this mod as i need it for running a x10 server and it just so happened to fail on start up. Ive installed the lastest version into the Source mod dirrectories and it comes back with an error everytime. Ill link the error some time in the morning as i shut my machine down before getting the logs and ill send them over your way asap. Hopefully it isnt to big of an issue

**Comment by unown294** [comment]
L 01/07/2016 - 01:09:22: [SM] Displaying call stack trace for plugin "tf2attributes.smx":
L 01/07/2016 - 01:09:22: [SM]   [0]  Line 85, /home/forums/content/files/8/4/3/0/4/116848.attach::OnPluginStart()
L 01/07/2016 - 01:09:22: [SM] Unable to load plugin "tf2x10.smx": Could not find required plugin "updater"
L 01/07/2016 - 01:09:22: [admin-flatfile.smx] Error(s) detected parsing addons\sourcemod\configs\admins_simple.ini
L 01/07/2016 - 01:09:22: [admin-flatfile.smx]  (line 39) Invalid flag detected: .
L 01/07/2016 - 01:12:19: SourceMod error session started
L 01/07/2016 - 01:12:19: Info (map "ctf_2fort") (file "errors_20160107.log")
L 01/07/2016 - 01:12:19: [SM] Error parsing gameconfig file "c:\tf2\tf\addons\sourcemod\gamedata\tf2.attributes.txt":
L 01/07/2016 - 01:12:19: [SM] Error 1 on line 0, col 0: Stream failed to open
L 01/07/2016 - 01:12:19: [SM] Native "LoadGameConfigFile" reported: Unable to open tf2.attributes: File could not be opened: The system cannot find the file specified

**Comment by FlaminSarge** [comment]
The last 3 lines seem to indicate that you're missing the gamedata file.

**Comment by unown294** [comment]
So would this be something related to Tf2 or a missing file that is used by
the tf2attribute

**Comment by FlaminSarge** [comment]
You forgot a file that tf2attributes needs.

**Comment by unown294** [comment]
Ok. Thank you pointing that

**Comment by unown294** [comment]
Alright i figured out why the error was occur in the first place. I think this could have been my fault idk but i would let you know so you keep it in mind. The error was occuring because it was try to search for the "tf2.attributes.txt" where instead i had "tf2.attributes.txt.txt". I guess it happened when i was moving stuff or somewhere down the line but i wanted to inform you on my findings. Thanks again for helping me with the issue.
