### ISSUE TITLE
Just a little error

### ISSUE THREAD

**Issue by SuperzScoutz** [FlaminSarge/tf2attributes#20]
L 02/06/2018 - 22:07:26: SourceMod error session started
L 02/06/2018 - 22:07:26: Info (map "vsh_2fortdesk_v8") (file "errors_20180206.log")
L 02/06/2018 - 22:07:26: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName

**Comment by FlaminSarge** [comment]
The latest GitHub version removes all the unnecessary gamedata/SDKCall setup, including this.

**Comment by SuperzScoutz** [comment]
It fixed but one more thing this happened after I did what you said
L 02/07/2018 - 20:20:58: [SM] Exception reported: Could not initialize call to CEconItemSchema::GetAttributeDefinition
L 02/07/2018 - 20:20:58: [SM] Blaming: tf2attributes.smx
L 02/07/2018 - 20:20:58: [SM] Call stack trace:
L 02/07/2018 - 20:20:58: [SM]   [0] SetFailState
L 02/07/2018 - 20:20:58: [SM]   [1] Line 142, C:\sourcemod\tf2attributes\tf2attributes.sp::OnPluginStart
L 02/07/2018 - 20:20:58: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
