### ISSUE TITLE
Cant load TF2Attributes

### ISSUE THREAD

**Issue by WarriorUnit** [FlaminSarge/tf2attributes#23]
L 02/24/2018 - 15:23:20: [SM] Blaming: tf2attributes.smx
L 02/24/2018 - 15:23:20: [SM] Call stack trace:
L 02/24/2018 - 15:23:20: [SM]   [0] LoadGameConfigFile
L 02/24/2018 - 15:23:20: [SM]   [1] Line 85, C:\sourcemod\tf2attributes\tf2attributes.sp::OnPluginStart
L 02/24/2018 - 15:23:20: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
L 02/24/2018 - 15:27:17: SourceMod error session started
L 02/24/2018 - 15:27:17: Info (map "cp_dustbowl") (file "errors_20180224.log")
L 02/24/2018 - 15:27:17: [SM] Error parsing gameconfig file "C:\hlserver\tf2\tf\addons\sourcemod\gamedata\tf2.attributes.txt":
L 02/24/2018 - 15:27:17: [SM] Error 1 on line 0, col 0: Stream failed to open
L 02/24/2018 - 15:27:17: [SM] Exception reported: Unable to open tf2.attributes: File could not be opened: The system cannot find the file specified.
Is something wrong? Also, the gamedata crap is setup correctly

**Comment by FlaminSarge** [comment]
You usually have to restart the server for new gamedata. If you see "System cannot find the file specified" then there's a high chance that the server can't access the file for whatever reason.
