### ISSUE TITLE
TF2 Attributes errors

### ISSUE THREAD

**Issue by Bot748939** [FlaminSarge/tf2attributes#24]
L 03/03/2018 - 22:44:39: SourceMod error session started
L 03/03/2018 - 22:44:39: Info (map "pl_badwater") (file "errors_20180303.log")
L 03/03/2018 - 22:44:39: [SM] Unable to load plugin "tf2attributes_ubup.smx": Required extension "TF2Items" file("tf2items.ext.2.ep2v") not running
L 03/03/2018 - 22:51:12: SourceMod error session started
L 03/03/2018 - 22:51:12: Info (map "pl_badwater") (file "errors_20180303.log")
L 03/03/2018 - 22:51:12: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName
L 03/03/2018 - 22:51:12: [SM] Unable to load plugin "tf2attributes_ubup.smx": Could not find required plugin "tf2itemsinfo"
L 03/03/2018 - 22:53:24: SourceMod error session started
L 03/03/2018 - 22:53:24: Info (map "pl_badwater") (file "errors_20180303.log")
L 03/03/2018 - 22:53:24: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName
L 03/03/2018 - 22:53:36: [SM] Exception reported: Script execution timed out
L 03/03/2018 - 22:53:36: [SM] Blaming: tf2itemsinfo.smx
L 03/03/2018 - 22:53:37: [SM] Call stack trace:
L 03/03/2018 - 22:53:37: [SM]   [1] Line 1689, tf2itemsinfo.sp::GetAttribIDByName
L 03/03/2018 - 22:53:37: [SM]   [2] Line 1562, tf2itemsinfo.sp::PrecacheItemSchema
L 03/03/2018 - 22:53:37: [SM]   [3] Line 269, tf2itemsinfo.sp::OnPluginStart
L 03/03/2018 - 22:53:37: [SM] Unable to load plugin "tf2itemsinfo.smx": Error detected in plugin startup (see error logs)

**Comment by FlaminSarge** [comment]
That's a tf2itemsinfo.sp error...

The latest GitHub version of TF2Attributes removes the warning for "[tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName" if that's what is bothering you.
