### ISSUE TITLE
I can't ever seem to get this to work.

### ISSUE THREAD

**Issue by LuigiBox** [FlaminSarge/tf2attributes#27]
I've done some looking around for similar problems, and I've tried everything. Re-installing, updating gamedata.txt all that stuff but I get this every time.

> sm plugins load tf2attributes
L 06/26/2018 - 21:32:22: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName
L 06/26/2018 - 21:32:22: [SM] Exception reported: Could not initialize call to CEconItemSchema::GetAttributeDefinitionByName
L 06/26/2018 - 21:32:22: [SM] Blaming: tf2attributes.smx
L 06/26/2018 - 21:32:22: [SM] Call stack trace:
L 06/26/2018 - 21:32:22: [SM]   [0] SetFailState
L 06/26/2018 - 21:32:22: [SM]   [1] Line 153, /home/forums/content/files/8/4/3/0/4/116848.attach::OnPluginStart
[SM] Plugin tf2attributes.smx failed to load: Error detected in plugin startup (see error logs).

I don't know what any of this means, please help.

**Comment by SparklyCatTF2** [comment]
The signature for CEconItemSchema::GetAttributeDefinitionByName was updated, replace the signature for windows under CEconItemSchema::GetAttributeDefinitionByName with \x55\x8B\xEC\x83\xEC\x14\x53\x8B\x5D\x08\x56\x57\x8B\xF9\x85\xDB\x75\x2A\x33\xC0

**Comment by Sluethen** [comment]
Hey @SparklyCatTF2.
Where would a person get said signatures?

**Comment by SparklyCatTF2** [comment]
You can learn how to do it [here](https://wiki.alliedmods.net/Signature_Scanning). Also you can watch [this](https://www.youtube.com/watch?v=5Ic6F4wncJ8) (enable subtitles) video and [this] one too(https://www.youtube.com/watch?v=4T03pckoB5g) to better understand how they do it.

**Comment by FlaminSarge** [comment]
Updated the repo with the new Windows sig. Shortened it by four bytes, as the shorter one worked on my end.
