### ISSUE TITLE
tf2attributes.smx error

### ISSUE THREAD

**Issue by strichking** [FlaminSarge/tf2attributes#29]
L 07/19/2018 - 08:46:20: SourceMod error session started
L 07/19/2018 - 08:46:20: Info (map "2tpl_mine_alpine") (file "errors_20180719.log")
L 07/19/2018 - 08:46:20: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName

What might be the cause of this problem? I checked everything, updated to last version of sourcemod. Before opening my server I updated it and then the error was there. Last time I had it open was like a month ago, maybe and it was working fine. Already updated to latest version of tf2.attributes too but nothing seem to fix this error.

**Comment by FlaminSarge** [comment]
If it's just SetCustomName, that's old unused gamedata and doesn't actually break the plugin. The latest GitHub version removes the warning for it.

**Comment by strichking** [comment]
Okay. Thanks for the answer.
