### ISSUE TITLE
Plugin stops map spawned sentries from doing dmg

### ISSUE THREAD

**Issue by Derphammer** [FlaminSarge/tf2attributes#30]
So something strange is going on the plugin stops map spawned sentries from doing dmg to red team. on some maps they have them in obby or a sentry course and they do no dmg to players when they shoot them. 
Kinda at a loss here 

we have everything updated to the newest version btw.

**Comment by FlaminSarge** [comment]
I seriously doubt that tf2attributes is doing this; the plugin exists as a library for other plugins to use, and doesn't do anything on its own.

**Comment by Derphammer** [comment]
Sigh this is what 4 days of not sleeping gets you. I posted this in the wrong github lol. Was downloading this one and ment to post in another one. Please forgive my very stupid moment.
