### ISSUE TITLE
Errors when booting up server

### ISSUE THREAD

**Issue by Arynn24** [FlaminSarge/tf2attributes#33]
I only get one error about tf2attributes, and it's this.
`[tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName`
I have gotten everything setup in the right folders and stuff. Could someone send me or tell me how re-set it up that way I know I did it right?
EDIT: I used the .smx file, not the .sp file for compiling, do I have to compile with it?

**Comment by Arynn24** [comment]
Nevermind, just compile the .sp and not use the pre-compiled .smx!

**Comment by FlaminSarge** [comment]
Right, I haven't had the chance to do a formal release with the version that removes that message. It's just a warning rather than a failure so if you don't care you can use the smx.
