### ISSUE TITLE
Doesn't work with RTD? Missing .txt file?

### ISSUE THREAD

**Issue by JayBoom** [FlaminSarge/tf2attributes#39]
It says on the allied mods:
Installation (SM1.7+):
1) Place tf2attributes.smx ("Get Plugin" for tf2attributes.sp) in the server's sourcemod plugins folder (normally "addons/sourcemod/plugins/").
2) Place tf2.attributes.txt in the server's sourcemod gamedata folder (normally "addons/sourcemod/gamedata/").
3) Write or install a plugin that uses these natives. If writing the plugin, you will need to #include <tf2attributes>, which means you will need to place tf2attributes.inc in the "include" folder of wherever you develop/compile SourceMod plugins.

But there is no .txt?

**Comment by MAGNAT2645** [comment]
Use [nosoop's fork](https://github.com/nosoop/tf2attributes/releases).

**Comment by FlaminSarge** [comment]
The link to the txt is at the very top of the alliedmods post
