### ISSUE TITLE
TF2 Atributes doesn't load correctly 

### ISSUE THREAD

**Issue by 123hotdog1100** [FlaminSarge/tf2attributes#4]
what keeps popping up in the console
[SM] Error parsing gameconfig file "C:\Users\Administrator\Desktop\SteamCMD\tf2\tf\addons\sourcemod\gamedata\tf2.attributes.txt":
L 12/12/2016 - 19:36:13: [SM] Error 1 on line 0, col 0: Stream failed to open
L 12/12/2016 - 19:36:13: [SM] Exception reported: Unable to open tf2.attributes: File could not be opened: The system cannot find the file specified.

L 12/12/2016 - 19:36:13: [SM] Blaming: tf2attributes.smx
L 12/12/2016 - 19:36:13: [SM] Call stack trace:
L 12/12/2016 - 19:36:13: [SM]   [0] LoadGameConfigFile
L 12/12/2016 - 19:36:13: [SM]   [1] Line 85, /home/forums/content/files/8/4/3/0/4/116848.attach::OnPluginStart
L 12/12/2016 - 19:36:13: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
L 12/12/2016 - 19:36:13: [SM] Unable to load plugin "tf2x10.smx": Could not find required plugin "tf2attributes"

i wouldn't mind help as i need this for a x10 server

**Comment by FlaminSarge** [comment]
You're missing the gamedata file, which is tf2.attributes.txt. Look for it and see if you can figure out how to set it up properly yourself, and if you can't, I'll try to point you in the right direction.
