### ISSUE TITLE
Error when starting up the plugin, causing it to unload

### ISSUE THREAD

**Issue by SleepyThiccBoi** [FlaminSarge/tf2attributes#42]
![Screenshot_32](https://user-images.githubusercontent.com/52759847/100401921-caa20780-3052-11eb-98e9-4404e4678252.png)

I know this is an old plugin and all, but it seems like it doesn't work at all, even if i try anything at all. I just want to get most of my plugins working with it (set health, resizeme, etc.)

I really want this to be fixed. Please and thank you.

**Comment by MAGNAT2645** [comment]
Try to use [nosoop's fork](https://github.com/nosoop/tf2attributes), works fine.

**Comment by SleepyThiccBoi** [comment]
> Try to use [nosoop's fork](https://github.com/nosoop/tf2attributes), works fine.

Thank you very much, it worked now, finally. I've been looking for a solution for a while now and you saved me. Thank you.
