### ISSUE TITLE
TF2 Attributes won't load properly

### ISSUE THREAD

**Issue by TheOverlordBunny** [FlaminSarge/tf2attributes#45]
I have the .smx and tf2.attributes.txt installed to plugins and gamedata respectively 
Error Log:

tf2attributes.smx ([TF2] TF2Attributes): Error detected in plugin startup (see error logs)
Errors:
cw3\attributes\aw2attrib.smx (Custom Weapons 3: AW2 Attributes): Library not found: tf2attributes
cw3\attributes\moreaw2.smx (Custom Weapons: More Advanced Weaponiser 2 Attributes): Library not found: tf2attributes
cw3\attributes\orion.smx (Custom Weapons: Orion's Attributes): Library not found: tf2attributes
cw3\attributes\rays-attributes.smx (Custom Weapons 3: Ray's Attributes): Library not found: tf2attributes
cw3\modules\cw2attributes.smx (Custom Weapons 3: CW2 Attributes Module): Library not found: tf2attributes
cw3\modules\cw2sounds.smx (Custom Weapons 3: CW2 Sound Module): Library not found: tf2attributes
cw3\modules\cw3-attributes.smx (Custom Weapons 3: Attributes Module): Library not found: tf2attributes
cw3.smx (Custom Weapons 3): Library not found: tf2attributes
killstreak_drn.smx (Killstreak for Everyone): Library not found: tf2attributes

It says there is no tf2attributes library, but I don't know how to create said library.

Another error thing:    32 <Error> "[TF2] TF2Attributes" (1.2.1) by FlaminSarge

**Comment by MAGNAT2645** [comment]
There should be more info about tf2attributes in the error log.

**Comment by TheOverlordBunny** [comment]
Oh, sorry about that, also, I'm running SourceMod


L 07/22/2021 - 15:28:00: SourceMod error session started
L 07/22/2021 - 15:28:00: Info (map "mvm_coaltown") (file "E:\SteamLibrary-Large\steamapps\common\Team Fortress 2\tf\addons\sourcemod\logs\errors_20210722.log")
**L 07/22/2021 - 15:28:00: [SM] Exception reported: Could not initialize call to CEconItemSchema::GetAttributeDefinition
L 07/22/2021 - 15:28:00: [SM] Blaming: tf2attributes.smx**
L 07/22/2021 - 15:28:00: [SM] Call stack trace:
L 07/22/2021 - 15:28:00: [SM]   [0] SetFailState
L 07/22/2021 - 15:28:00: [SM]   [1] Line 126, /home/forums/content/files/2/5/2/7/8/7/175903.attach::OnPluginStart
**L 07/22/2021 - 15:28:00: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)**
L 07/22/2021 - 15:28:00: [SM] Unable to load plugin "tf2_taunts_tf2idb.smx": Could not find required plugin "tf2itemsinfo"
L 07/22/2021 - 15:28:18: [SM] Exception reported: Invalid file handle 0 (error 4)
L 07/22/2021 - 15:28:18: [SM] Blaming: mushroomhealth.smx
L 07/22/2021 - 15:28:18: [SM] Call stack trace:
L 07/22/2021 - 15:28:18: [SM]   [0] ReadDirEntry
L 07/22/2021 - 15:28:18: [SM]   [1] Line 137, /home/forums/content/files/1/5/1/2/6/31042.attach::AddFolderToDownloadTable
L 07/22/2021 - 15:28:18: [SM]   [2] Line 49, /home/forums/content/files/1/5/1/2/6/31042.attach::OnMapStart
L 07/22/2021 - 15:48:44: Error log file session closed.
L 07/22/2021 - 15:48:44: SourceMod error session started
L 07/22/2021 - 15:48:44: Info (map "cp_dustbowl") (file "E:\SteamLibrary-Large\steamapps\common\Team Fortress 2\tf\addons\sourcemod\logs\errors_20210722.log")
**L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "cw3\attributes\aw2attrib.smx": Could not find required plugin "tf2attributes"
L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "cw3\attributes\moreaw2.smx": Could not find required plugin "tf2attributes"
L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "cw3\attributes\orion.smx": Could not find required plugin "tf2attributes"
L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "cw3\attributes\rays-attributes.smx": Could not find required plugin "tf2attributes"
L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "cw3\modules\cw2attributes.smx": Could not find required plugin "tf2attributes"
L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "cw3\modules\cw2sounds.smx": Could not find required plugin "tf2attributes"
L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "cw3\modules\cw3-attributes.smx": Could not find required plugin "tf2attributes"
L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "cw3.smx": Could not find required plugin "tf2attributes"
L 07/22/2021 - 15:48:44: [SM] Unable to load plugin "killstreak_drn.smx": Could not find required plugin "tf2attributes"**
L 07/22/2021 - 15:48:49: [SM] Exception reported: Invalid file handle 0 (error 4)
L 07/22/2021 - 15:48:49: [SM] Blaming: mushroomhealth.smx
L 07/22/2021 - 15:48:49: [SM] Call stack trace:
L 07/22/2021 - 15:48:49: [SM]   [0] ReadDirEntry
L 07/22/2021 - 15:48:49: [SM]   [1] Line 137, /home/forums/content/files/1/5/1/2/6/31042.attach::AddFolderToDownloadTable
L 07/22/2021 - 15:48:49: [SM]   [2] Line 49, /home/forums/content/files/1/5/1/2/6/31042.attach::OnMapStart
L 07/22/2021 - 15:48:52: Error log file session closed.

**Comment by TheOverlordBunny** [comment]
It's been over a year, I got a new PC, and decided to try again with this plugin. It still doesn't work, however this time I remembered to install tf2.attributes.txt, but it still doesn't work. Any help?

ERROR LOGS:

L 12/22/2022 - 14:37:50: SourceMod error session started
L 12/22/2022 - 14:37:50: Info (map "ctf_2fort") (file "C:\Program Files (x86)\Steam\steamapps\common\team fortress 2\tf\addons\sourcemod\logs\errors_20221222.log")
L 12/22/2022 - 14:37:50: [SM] Error parsing gameconfig file "C:\Program Files (x86)\Steam\steamapps\common\team fortress 2\tf\addons\sourcemod\gamedata\tf2.attributes.txt":
L 12/22/2022 - 14:37:50: [SM] Error 1 on line 0, col 0: Stream failed to open
L 12/22/2022 - 14:37:50: [SM] Exception reported: Unable to open tf2.attributes: File could not be opened: The system cannot find the file specified.


L 12/22/2022 - 14:37:50: [SM] Blaming: tf2attributes.smx
L 12/22/2022 - 14:37:50: [SM] Call stack trace:
L 12/22/2022 - 14:37:50: [SM]   [0] LoadGameConfigFile
L 12/22/2022 - 14:37:50: [SM]   [1] Line 126, scripting/tf2attributes.sp::OnPluginStart
L 12/22/2022 - 14:37:50: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
L 12/22/2022 - 14:39:10: SourceMod error session started
L 12/22/2022 - 14:39:10: Info (map "ctf_2fort") (file "C:\Program Files (x86)\Steam\steamapps\common\team fortress 2\tf\addons\sourcemod\logs\errors_20221222.log")
L 12/22/2022 - 14:39:10: [SM] Error parsing gameconfig file "C:\Program Files (x86)\Steam\steamapps\common\team fortress 2\tf\addons\sourcemod\gamedata\tf2.attributes.txt":
L 12/22/2022 - 14:39:10: [SM] Error 1 on line 0, col 0: Stream failed to open
L 12/22/2022 - 14:39:10: [SM] Exception reported: Unable to open tf2.attributes: File could not be opened: The system cannot find the file specified.


L 12/22/2022 - 14:39:10: [SM] Blaming: tf2attributes.smx
L 12/22/2022 - 14:39:10: [SM] Call stack trace:
L 12/22/2022 - 14:39:10: [SM]   [0] LoadGameConfigFile
L 12/22/2022 - 14:39:10: [SM]   [1] Line 126, scripting/tf2attributes.sp::OnPluginStart
L 12/22/2022 - 14:39:10: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
L 12/22/2022 - 14:41:09: [SM] Exception reported: Could not initialize call to CEconItemSchema::GetItemDefinition
L 12/22/2022 - 14:41:09: [SM] Blaming: tf2attributes.smx
L 12/22/2022 - 14:41:09: [SM] Call stack trace:
L 12/22/2022 - 14:41:09: [SM]   [0] SetFailState
L 12/22/2022 - 14:41:09: [SM]   [1] Line 137, scripting/tf2attributes.sp::OnPluginStart
L 12/22/2022 - 14:41:09: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
L 12/22/2022 - 14:44:58: Error log file session closed.
L 12/22/2022 - 14:44:58: SourceMod error session started
L 12/22/2022 - 14:44:58: Info (map "ctf_2fort") (file "C:\Program Files (x86)\Steam\steamapps\common\team fortress 2\tf\addons\sourcemod\logs\errors_20221222.log")
L 12/22/2022 - 14:44:58: [SM] Unable to load plugin "cw3\attributes\aw2attrib.smx": Could not find required plugin "tf2attributes"
L 12/22/2022 - 14:44:58: [SM] Unable to load plugin "cw3\attributes\rays-attributes.smx": Could not find required plugin "tf2attributes"
L 12/22/2022 - 14:44:58: [SM] Unable to load plugin "cw3\modules\cw2attributes.smx": Could not find required plugin "tf2attributes"
L 12/22/2022 - 14:44:58: [SM] Unable to load plugin "cw3\modules\cw2sounds.smx": Could not find required plugin "tf2attributes"
L 12/22/2022 - 14:44:58: [SM] Unable to load plugin "cw3\modules\cw3-attributes.smx": Could not find required plugin "tf2attributes"
L 12/22/2022 - 14:44:58: [SM] Unable to load plugin "cw3.smx": Could not find required plugin "tf2attributes"
L 12/22/2022 - 14:47:20: Error log file session closed.
L 12/22/2022 - 14:47:20: SourceMod error session started
L 12/22/2022 - 14:47:20: Info (map "ctf_2fort") (file "C:\Program Files (x86)\Steam\steamapps\common\team fortress 2\tf\addons\sourcemod\logs\errors_20221222.log")
L 12/22/2022 - 14:47:20: [SM] Unable to load plugin "cw3\attributes\basic-attributes.smx": Could not find required plugin "cw3-attributes"
L 12/22/2022 - 14:47:20: [SM] Unable to load plugin "cw3\modules\cw2model-application.smx": Could not find required plugin "cw3"

**Comment by TheOverlordBunny** [comment]
This time it's a completely vanilla server apart from the necessary plugins and... well... sourcemod... obviously.

**Comment by nosoop** [comment]
If you installed the gamedata and reloaded the plugin while the server was running, you should be good to go after a server restart.  SourceMod does caching of failed gamedata internally.

Also make sure that you're using the latest release; prior to being brought upstream the releases were not current.

**Comment by TheOverlordBunny** [comment]
Thanks! It turned out I has an outdated version of tf2items installed and put the gamedata files into config lol

**Comment by TheCrazedbreadmann** [comment]
mine dont work even with files in help
