### ISSUE TITLE
Error in plugin startup: Could not initialize call to CTFPlayer::AddCustomAttribute

### ISSUE THREAD

**Issue by RealStillkill** [FlaminSarge/tf2attributes#47]
I'm encountering an error on startup which prevents the plugin from loading. All the relevant files are in place and I have no idea where to go from here.

Error log
```
L 01/27/2023 - 00:15:06: SourceMod error session started
L 01/27/2023 - 00:15:06: Info (map "vsh_atollday_v5a") (file "/srv/gameservers/tff_vsh_server_1/tf/addons/sourcemod/logs/errors_20230127.log")
L 01/27/2023 - 00:15:06: [SM] Exception reported: Could not initialize call to CTFPlayer::AddCustomAttribute
L 01/27/2023 - 00:15:06: [SM] Blaming: tf2attributes.smx
L 01/27/2023 - 00:15:06: [SM] Call stack trace:
L 01/27/2023 - 00:15:06: [SM]   [0] SetFailState
L 01/27/2023 - 00:15:06: [SM]   [1] Line 229, scripting/tf2attributes.sp::OnPluginStart
```

Sourcemod is updated to latest
tf2attributes is updated to latest

**Comment by nosoop** [comment]
Make sure the gamedata is also up to date and restart the server to ensure you're not operating off of a cached copy.

**Comment by nosoop** [comment]
Don't think there's anything actionable left; I assume this has resolved itself in some way.
