### ISSUE TITLE
My server can't load this.

### ISSUE THREAD

**Issue by SuperIsakSwahn** [FlaminSarge/tf2attributes#49]
I put the smx and txt files in the folders it says you put them in, but when starting my server, I get this message: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
If I put the paths to these in the metaplugins.ini, I get error 0xc000012f.

;If your plugin came with a .vdf file, you do not need to use this file.
;
;List one plugin per line.  Each line should contain the path to the plugin's binary.
;Any line starting with a ';' character is a comment line, and is ignored.
;
;You do not need to include the _i486.so or .dll part of the file name.  Example:
; addons/sourcemod/bin/sourcemod_mm
;You may also put an alias in front of the file, for example:
; sm addons/sourcemod/bin/sourcemod_mm
;Will allow you to use "meta load sm" from the console.
;
addons/sourcemod/bin/sourcemod_mm
;********* LIST PLUGINS BELOW ***********
c:\tf2server\tf\addons\sourcemod\plugins\tf2attributes.smx
c:\tf2server\tf\addons\sourcemod\gamedata\tf2.attributes.txt this is the metaplugins.ini.

**Comment by nosoop** [comment]
It's not a Metamod:Source plugin, so adding it to any `.ini` file is not necessary.

Please report back with the output from your SourceMod error logs (`addons/sourcemod/logs/errors_20240108.txt`; adjust the date as needed).

**Comment by SuperIsakSwahn** [comment]
errors_20240109.log from running the server with the plugin cleared from the .ini:
L 01/09/2024 - 02:28:35: SourceMod error session started
L 01/09/2024 - 02:28:35: Info (map "cp_dustbowl") (file "C:\TF2Server\tf\addons\sourcemod\logs\errors_20240109.log")
L 01/09/2024 - 02:28:35: [SM] Exception reported: Could not initialize call to CAttributeManager::ApplyAttributeStringWrapper
L 01/09/2024 - 02:28:35: [SM] Blaming: tf2attributes.smx
L 01/09/2024 - 02:28:35: [SM] Call stack trace:
L 01/09/2024 - 02:28:35: [SM]   [0] SetFailState
L 01/09/2024 - 02:28:35: [SM]   [1] Line 295, scripting/tf2attributes.sp::OnPluginStart
L 01/09/2024 - 02:28:35: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
L 01/09/2024 - 02:28:35: [SM] Unable to load plugin "tf2item_cosmetics.smx": Could not find required plugin "tf2attributes"
L 01/09/2024 - 02:28:35: [SM] Unable to load plugin "tf2item_weapons.smx": Could not find required plugin "tf2attributes"
L 01/09/2024 - 02:28:35: [SM] Unable to load plugin "vip-unusual-glow.smx": Could not find required plugin "tf2attributes"
L 01/09/2024 - 02:41:01: Error log file session closed.

**Comment by nosoop** [comment]
Since that function is one of the later ones, it sounds like you're using a gamedata file designed for an older version of tf2attributes; please ensure both files are from the same release ([current](https://github.com/FlaminSarge/tf2attributes/releases/tag/v1.7.3)), that you're certain that it's in the correct location (`addons/sourcemod/gamedata/tf2.attributes.txt`), and that you've restarted the server afterwards just to ensure SourceMod's gamedata file caching isn't interfering.

**Comment by SuperIsakSwahn** [comment]
I don't know how, but I did what you said (which I believe I did before) and now my plugins seem to work. But when I do Meta List, this is everything that shows up, does tf2 attributes not appear in this list normally?

meta list
Listing 5 plugins:
  [01] SourceMod (1.11.0.6952) by AlliedModders LLC
  [02] TF2Items (1.6.4) by Asherkin & AzuiSleet & Damizean
  [03] TF2 Tools (1.11.0.6952) by AlliedModders LLC
  [04] SDK Hooks (1.11.0.6952) by AlliedModders LLC
  [05] SDK Tools (1.11.0.6952) by AlliedModders LLC

**Comment by nosoop** [comment]
As I said before, tf2attributes is not a Metamod:Source plugin, so it will not show up in `meta list` (it does show in `sm plugins list`, as it is a SourceMod plugin).

Thanks for confirming that it works; will go ahead and mark this as resolved.
