### ISSUE TITLE
Server crashes when using some values since plug-in 1.7.3.1 update

### ISSUE THREAD

**Issue by DongRyeok** [FlaminSarge/tf2attributes#54]
Hello.

The plugin has also been updated to 1.7.3.1 after the game data update for 2024-04-18 Team Fortress 2.

However, since the update, we have been experiencing the following problems.

There is a problem that the server crashes when adjusting the value to TF2Attrib_SetByDefIndex.

The RTD plugin using the tf2attributes plugin as a dependency also has a problem that the server crashes when Perks using the TF2Attrib_SetByDefIndex value occurs.

The TF2 server is running on Windows and the SourceMod version in use is 1.11.0-git6956.

**Comment by nosoop** [comment]
Should be resolved with [v1.7.3.2](https://github.com/FlaminSarge/tf2attributes/releases/tag/v1.7.3.2).

**Comment by DongRyeok** [comment]
Thank you.

Problem solved.
