### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by AaRCaT** [FlaminSarge/tf2attributes#58]
L 10/07/2024 - 04:25:11: [SM] Exception reported: Could not initialize call to CEconItemSchema::GetItemDefinition
L 10/07/2024 - 04:25:12: [SM] Blaming: tf2attributes.smx
L 10/07/2024 - 04:25:12: [SM] Call stack trace:
L 10/07/2024 - 04:25:12: [SM]   [0] SetFailState
L 10/07/2024 - 04:25:12: [SM]   [1] Line 137, /scratch/scripting/tf2attributes.sp::OnPluginStart
L 10/07/2024 - 04:25:12: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)

**Comment by nosoop** [comment]
Likely one of two issues:
- Gamedata not installed. Ensure you've installed all the files from [the latest release](https://github.com/FlaminSarge/tf2attributes/releases/tag/v1.7.3.3), including the `tf2.attributes.txt` file.
- You're running a 64-bit dedicated server; that is currently not supported.

**Comment by AaRCaT** [comment]
Nevermind, i was installed another server, run without plugins works
i put some plugins and exts, then run server, All works

Some plugins, exts or something bad server error crash in old server.
