### ISSUE TITLE
TF2Attributes error

### ISSUE THREAD

**Issue by VirtualPlauge** [FlaminSarge/tf2attributes#6]
L 03/04/2017 - 15:55:10: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)

**Comment by FlaminSarge** [comment]
Where are the error logs that it asks you to look at?

**Comment by VirtualPlauge** [comment]
L 03/04/2017 - 18:01:03: [SM] Exception reported: Could not initialize call to CAttributeList::SetRuntimeAttributeValue
L 03/04/2017 - 18:01:03: [SM] Blaming: tf2attributes.smx
L 03/04/2017 - 18:01:03: [SM] Call stack trace:
L 03/04/2017 - 18:01:03: [SM]   [0] SetFailState
L 03/04/2017 - 18:01:03: [SM]   [1] Line 176, /home/groups/sourcemod/upload_tmp/phpTlBE7W.sp::OnPluginStart
L 03/04/2017 - 18:01:03: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)

**Comment by VirtualPlauge** [comment]
That's all I can find.

**Comment by VirtualPlauge** [comment]
I still need help, you know.

**Comment by FlaminSarge** [comment]
The only thing I can think of when it can't initialize SDKCalls is that the gamedata is incorrect, but somebody already posted the updated gamedata for the TF2 toolchain beta, and I assumed you already tried that, since there's already a pull request/issue up for it and I figured you'd have checked already open issues before posting yours, so I'm stumped.

**Comment by VirtualPlauge** [comment]
@FlaminSarge Yes, I've done all of that, so there's no way for you to fix it?

**Comment by VirtualPlauge** [comment]
I'm not sure if my server is running the toolchain beta, though.

**Comment by Benoist3012** [comment]
"I'm not sure if my server is running the toolchain beta, though."
Well if you used the gamedata I posted and your server weren't on the beta build that would explain why you couldn't run it. But anyway, as from yesterday's update all servers are running on the beta build now, so you shouldn't get any new problem now.

**Comment by FlaminSarge** [comment]
Closing since no updates for about a month

**Comment by Enderman1444** [comment]
ok
