### ISSUE TITLE
Help tf2 attributes doesnt load 

### ISSUE THREAD

**Issue by SuperzScoutz** [FlaminSarge/tf2attributes#7]
L 03/20/2017 - 21:26:33: [SM] Blaming: tf2attributes.smx
L 03/20/2017 - 21:26:33: [SM] Call stack trace:
L 03/20/2017 - 21:26:33: [SM]   [0] LoadGameConfigFile
L 03/20/2017 - 21:26:33: [SM]   [1] Line 85, /home/forums/content/files/8/4/3/0/4/116848.attach::OnPluginStart
L 03/20/2017 - 21:26:33: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)
L 03/20/2017 - 21:56:19: SourceMod error session started
L 03/20/2017 - 21:56:19: Info (map "vsh_2fortdesk_v8") (file "errors_20170320.log")
L 03/20/2017 - 21:56:19: [SM] Exception reported: Could not initialize call to CEconItemSchema::GetAttributeDefinition
L 03/20/2017 - 21:56:19: [SM] Blaming: tf2attributes.smx
L 03/20/2017 - 21:56:19: [SM] Call stack trace:
L 03/20/2017 - 21:56:19: [SM]   [0] SetFailState
L 03/20/2017 - 21:56:19: [SM]   [1] Line 142, /home/forums/content/files/8/4/3/0/4/116848.attach::OnPluginStart
L 03/20/2017 - 21:56:19: [SM] Unable to load plugin "tf2attributes.smx": Error detected in plugin startup (see error logs)

**Comment by FlaminSarge** [comment]
Gamedata. Can you avoid posting an issue before trying to just update/reinstall everything?

**Comment by SuperzScoutz** [comment]
ok it fixed
